15.01.2021 - 07:24:53 - [TAB v2.8.10] An error occurred when refreshing placeholders
15.01.2021 - 07:24:53 - java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@66f626b5 rejected from java.util.concurrent.ThreadPoolExecutor@67c84b02[Shutting down, pool size = 2, active threads = 2, queued tasks = 0, completed tasks = 469489]
15.01.2021 - 07:24:53 -        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
15.01.2021 - 07:24:53 -        at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
15.01.2021 - 07:24:53 -        at java.util.concurrent.ThreadPoolExecutor.execute(Unknown Source)
15.01.2021 - 07:24:53 -        at java.util.concurrent.AbstractExecutorService.submit(Unknown Source)
15.01.2021 - 07:24:53 -        at me.neznamy.tab.shared.cpu.CPUManager.runTask(CPUManager.java:92)
15.01.2021 - 07:24:53 -        at me.neznamy.tab.shared.features.PlaceholderManager.refresh(PlaceholderManager.java:155)
15.01.2021 - 07:24:53 -        at me.neznamy.tab.shared.features.PlaceholderManager.access$000(PlaceholderManager.java:37)
15.01.2021 - 07:24:53 -        at me.neznamy.tab.shared.features.PlaceholderManager$1.run(PlaceholderManager.java:121)
15.01.2021 - 07:24:53 -        at me.neznamy.tab.shared.cpu.CPUManager$4.run(CPUManager.java:119)
15.01.2021 - 07:24:53 -        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
15.01.2021 - 07:24:53 -        at java.util.concurrent.FutureTask.run(Unknown Source)
15.01.2021 - 07:24:53 -        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
15.01.2021 - 07:24:53 -        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
15.01.2021 - 07:24:59 -        at java.lang.Thread.run(Unknown Source)
